name: Invite me to the EliteDevSolution Tech

description: I would like to be part of the awesome EliteDevSolution Tech

title: "Please invite me to the EliteDevSolution Tech"

labels: [✉️ github-invitation]

body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true

  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you meet EliteDevSolution Tech? What do you like about this EliteDevSolution Tech? Why do you want to join?
      placeholder: I would like to be part of the awesome team
    validations:
      required: false
